import { CardItem, NewsItem, WholesalePack, AuctionItem } from './types';

export const mockBanks = [
  'CHASE BANK',
  'BANK OF AMERICA',
  'WELLS FARGO',
  'CITIBANK',
  'CAPITAL ONE',
  'BARCLAYS',
  'HSBC',
  'ROYAL BANK OF CANADA',
  'LLOYDS BANK',
  'SANTANDER',
  'DEUTSCHE BANK',
  'SOCIETE GENERALE',
];

export const mockCountries = [
  { code: 'US', name: 'United States' },
  { code: 'CA', name: 'Canada' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'AU', name: 'Australia' },
  { code: 'IT', name: 'Italy' },
  { code: 'ES', name: 'Spain' },
];

export const mockStates = [
  'CA', 'NY', 'TX', 'FL', 'GA', 'IL', 'PA', 'OH', 'MI', 'NC', 'WA',
  'ON', 'QC', 'BC', 'AB',
  'LND', 'MAN', 'BIR',
  'BY', 'NW', 'HE',
];

export const mockBases = [
  'BASE_SUMMER_SURGE_2026',
  'BASE_ELITE_GOLD_MIX',
  'BASE_EURO_DUMPS_UPDATED',
  'BASE_AMEX_SPECIAL_CORP',
  'BASE_GLOBAL_RELOAD',
];

export const mockNews: NewsItem[] = [
  {
    id: 'news-1',
    title: '🔥 CORE BASE UPDATE: BASE_SUMMER_SURGE_2026 ADDED',
    date: '2026-06-23',
    content: 'We have uploaded a fresh, high-validity base containing Visa Infinite, Mastercard World Elite, and Amex Centurion elements. Excellent validity rate verified! Get your bins before they are filtered.',
    important: true,
  },
  {
    id: 'news-2',
    title: '📢 10% TOP-UP DEPOSIT BONUS SPECIAL',
    date: '2026-06-20',
    content: 'Due to cryptocurrency market adjustments, all deposits made via Bitcoin (BTC), Litecoin (LTC), or Ethereum (ETH) will receive an automatic +10% bonus added to your balance. Promo ends in 48 hours!',
    important: true,
  },
  {
    id: 'news-3',
    title: '🛡️ SUPPORT TICKETS SYSTEM IMPROVEMENTS',
    date: '2026-06-15',
    content: 'To handle user inquiries faster, we have added more staff to the Support Ticket department. Support is now online 24/7. Average response time has been reduced to under 15 minutes.',
    important: false,
  },
  {
    id: 'news-4',
    title: '⚠️ RE-CHECK SYSTEM AND REFUND PERIOD POLICY',
    date: '2026-06-10',
    content: 'Please note that cards marked as "Only Refundable" can be checked with our built-in tester within 15 minutes of purchase. Non-working cards will be auto-refunded to your balance. Normal items are sold as-is with lower rates.',
    important: false,
  },
];

export const mockWholesalePacks: WholesalePack[] = [
  {
    id: 'pack-1',
    name: '🇺🇸 Starter US Mix Pack',
    count: 10,
    price: 45.00,
    description: 'Great for beginners. Assorted US Visa/Mastercard credit and debit cards. High valid rate guaranteed.',
    country: 'US',
    type: 'Visa & Mastercard',
  },
  {
    id: 'pack-2',
    name: '🇪🇺 Elite Europe Pack',
    count: 25,
    price: 150.00,
    description: 'High-tier European credit items (Germany, UK, France). Excellent for premium diagnostic checkups.',
    country: 'DE/GB/FR',
    type: 'Gold & Platinum Credit',
  },
  {
    id: 'pack-3',
    name: '🌎 Global Enterprise Bundle',
    count: 50,
    price: 250.00,
    description: 'Bulky random mix of worldwide records including Corporate and Business Infinite cards. Super discounted price!',
    country: 'MIXED',
    type: 'Business/Corp/Infinite',
  },
];

export const mockAuctionItems = (): AuctionItem[] => {
  // Endtimes are future dates
  const futureTime = (hours: number) => {
    const d = new Date();
    d.setMinutes(d.getMinutes() + hours * 60);
    return d.toISOString();
  };

  return [
    {
      id: 'auc-1',
      card: {
        id: 'auc-card-1',
        bin: '371245',
        type: 'Amex',
        subtype: 'Corporate',
        creditDebit: 'Credit',
        country: 'US',
        state: 'NY',
        zip: '10003',
        bank: 'AMERICAN EXPRESS',
        expDate: '09/28',
      },
      currentBid: 12.00,
      myBid: 0,
      bidsCount: 4,
      endTime: futureTime(1.5),
    },
    {
      id: 'auc-2',
      card: {
        id: 'auc-card-2',
        bin: '453271',
        type: 'Visa',
        subtype: 'Signature',
        creditDebit: 'Credit',
        country: 'CA',
        state: 'ON',
        zip: 'M5H 2',
        bank: 'ROYAL BANK OF CANADA',
        expDate: '11/27',
      },
      currentBid: 15.50,
      myBid: 0,
      bidsCount: 7,
      endTime: futureTime(3),
    },
    {
      id: 'auc-3',
      card: {
        id: 'auc-card-3',
        bin: '541275',
        type: 'Mastercard',
        subtype: 'Platinum',
        creditDebit: 'Debit',
        country: 'GB',
        state: 'LND',
        zip: 'EC1A',
        bank: 'BARCLAYS BANK',
        expDate: '02/29',
      },
      currentBid: 8.00,
      myBid: 0,
      bidsCount: 2,
      endTime: futureTime(0.5),
    },
  ];
};

export const mockCardsList: CardItem[] = [
  {
    id: 'card-1',
    bin: '411111',
    zip: '90210',
    bank: 'CHASE BANK',
    country: 'US',
    state: 'CA',
    type: 'Visa',
    creditDebit: 'Credit',
    subtype: 'Platinum',
    expDate: '12/28',
    discounted: true,
    onlyRefundable: true,
    price: 15.00,
    ssn: true,
    dob: true,
    mmn: false,
    ipAddress: '192.168.1.1',
    lastPaidAmount: true,
    driverLicense: true,
    driverLicenseScan: false,
    atmPin: false,
    attPin: false,
    fullAddress: true,
    phone: true,
    email: true,
    emailPassword: true,
    withoutCvv2: false,
    base: 'BASE_SUMMER_SURGE_2026',
  },
  {
    id: 'card-2',
    bin: '542418',
    zip: '10019',
    bank: 'CITIBANK',
    country: 'US',
    state: 'NY',
    type: 'Mastercard',
    creditDebit: 'Credit',
    subtype: 'Gold',
    expDate: '05/27',
    discounted: false,
    onlyRefundable: false,
    price: 10.00,
    ssn: true,
    dob: false,
    mmn: false,
    ipAddress: '68.12.43.190',
    lastPaidAmount: false,
    driverLicense: false,
    driverLicenseScan: false,
    atmPin: false,
    attPin: false,
    fullAddress: true,
    phone: true,
    email: false,
    emailPassword: false,
    withoutCvv2: false,
    base: 'BASE_ELITE_GOLD_MIX',
  },
  {
    id: 'card-3',
    bin: '371349',
    zip: '30309',
    bank: 'AMERICAN EXPRESS',
    country: 'US',
    state: 'GA',
    type: 'Amex',
    creditDebit: 'Credit',
    subtype: 'Corporate',
    expDate: '08/28',
    discounted: false,
    onlyRefundable: true,
    price: 25.00,
    ssn: true,
    dob: true,
    mmn: true,
    ipAddress: '172.56.21.99',
    lastPaidAmount: true,
    driverLicense: true,
    driverLicenseScan: true,
    atmPin: false,
    attPin: true,
    fullAddress: true,
    phone: true,
    email: true,
    emailPassword: true,
    withoutCvv2: false,
    base: 'BASE_AMEX_SPECIAL_CORP',
  },
  {
    id: 'card-4',
    bin: '422315',
    zip: 'M5V 2H1',
    bank: 'ROYAL BANK OF CANADA',
    country: 'CA',
    state: 'ON',
    type: 'Visa',
    creditDebit: 'Debit',
    subtype: 'Classic',
    expDate: '02/29',
    discounted: true,
    onlyRefundable: false,
    price: 8.50,
    ssn: false,
    dob: false,
    mmn: false,
    ipAddress: '198.162.4.52',
    lastPaidAmount: false,
    driverLicense: false,
    driverLicenseScan: false,
    atmPin: true,
    attPin: false,
    fullAddress: true,
    phone: false,
    email: false,
    emailPassword: false,
    withoutCvv2: false,
    base: 'BASE_GLOBAL_RELOAD',
  },
  {
    id: 'card-5',
    bin: '519122',
    zip: 'EC1A 1BB',
    bank: 'BARCLAYS',
    country: 'GB',
    state: 'LND',
    type: 'Mastercard',
    creditDebit: 'Credit',
    subtype: 'Signature',
    expDate: '10/28',
    discounted: false,
    onlyRefundable: true,
    price: 18.00,
    ssn: false,
    dob: true,
    mmn: false,
    ipAddress: '82.45.101.2',
    lastPaidAmount: true,
    driverLicense: false,
    driverLicenseScan: false,
    atmPin: false,
    attPin: false,
    fullAddress: true,
    phone: true,
    email: true,
    emailPassword: false,
    withoutCvv2: false,
    base: 'BASE_EURO_DUMPS_UPDATED',
  },
  {
    id: 'card-6',
    bin: '601101',
    zip: '77002',
    bank: 'WELLS FARGO',
    country: 'US',
    state: 'TX',
    type: 'Discover',
    creditDebit: 'Credit',
    subtype: 'Classic',
    expDate: '01/27',
    discounted: true,
    onlyRefundable: false,
    price: 7.00,
    ssn: false,
    dob: false,
    mmn: false,
    ipAddress: '99.43.125.8',
    lastPaidAmount: false,
    driverLicense: false,
    driverLicenseScan: false,
    atmPin: false,
    attPin: false,
    fullAddress: true,
    phone: false,
    email: false,
    emailPassword: false,
    withoutCvv2: true,
    base: 'BASE_SUMMER_SURGE_2026',
  },
  {
    id: 'card-7',
    bin: '453218',
    zip: '33101',
    bank: 'BANK OF AMERICA',
    country: 'US',
    state: 'FL',
    type: 'Visa',
    creditDebit: 'Credit',
    subtype: 'Infinite',
    expDate: '06/29',
    discounted: false,
    onlyRefundable: true,
    price: 35.00,
    ssn: true,
    dob: true,
    mmn: true,
    ipAddress: '104.244.76.1',
    lastPaidAmount: true,
    driverLicense: true,
    driverLicenseScan: true,
    atmPin: true,
    attPin: true,
    fullAddress: true,
    phone: true,
    email: true,
    emailPassword: true,
    withoutCvv2: false,
    base: 'BASE_SUMMER_SURGE_2026',
  },
  {
    id: 'card-8',
    bin: '552312',
    zip: 'V5K 1A1',
    bank: 'ROYAL BANK OF CANADA',
    country: 'CA',
    state: 'BC',
    type: 'Mastercard',
    creditDebit: 'Debit',
    subtype: 'Corporate',
    expDate: '04/28',
    discounted: false,
    onlyRefundable: false,
    price: 14.00,
    ssn: false,
    dob: false,
    mmn: false,
    ipAddress: '24.80.12.99',
    lastPaidAmount: false,
    driverLicense: false,
    driverLicenseScan: false,
    atmPin: false,
    attPin: false,
    fullAddress: true,
    phone: true,
    email: true,
    emailPassword: false,
    withoutCvv2: false,
    base: 'BASE_GLOBAL_RELOAD',
  },
  {
    id: 'card-9',
    bin: '378211',
    zip: '20001',
    bank: 'AMERICAN EXPRESS',
    country: 'US',
    state: 'WA',
    type: 'Amex',
    creditDebit: 'Credit',
    subtype: 'Gold',
    expDate: '11/27',
    discounted: true,
    onlyRefundable: true,
    price: 12.50,
    ssn: true,
    dob: false,
    mmn: false,
    ipAddress: '128.59.10.12',
    lastPaidAmount: false,
    driverLicense: true,
    driverLicenseScan: false,
    atmPin: false,
    attPin: false,
    fullAddress: true,
    phone: true,
    email: false,
    emailPassword: false,
    withoutCvv2: false,
    base: 'BASE_ELITE_GOLD_MIX',
  },
  {
    id: 'card-10',
    bin: '480213',
    zip: '80301',
    bank: 'WELLS FARGO',
    country: 'US',
    state: 'CO',
    type: 'Visa',
    creditDebit: 'Debit',
    subtype: 'Business',
    expDate: '03/29',
    discounted: false,
    onlyRefundable: true,
    price: 20.00,
    ssn: true,
    dob: true,
    mmn: false,
    ipAddress: '74.125.19.10',
    lastPaidAmount: true,
    driverLicense: false,
    driverLicenseScan: false,
    atmPin: true,
    attPin: false,
    fullAddress: true,
    phone: true,
    email: true,
    emailPassword: false,
    withoutCvv2: false,
    base: 'BASE_SUMMER_SURGE_2026',
  },
  {
    id: 'bank-log-1',
    bin: 'LOGBANK',
    zip: '10001',
    bank: 'CHASE SAVINGS LOG',
    country: 'US',
    state: 'NY',
    type: 'Visa',
    creditDebit: 'Credit',
    subtype: 'Business',
    expDate: '06/29',
    discounted: false,
    onlyRefundable: true,
    price: 45.00,
    ssn: false,
    dob: false,
    mmn: false,
    ipAddress: '127.0.0.1',
    lastPaidAmount: false,
    driverLicense: false,
    driverLicenseScan: false,
    atmPin: false,
    attPin: false,
    fullAddress: false,
    phone: false,
    email: false,
    emailPassword: false,
    withoutCvv2: false,
    base: 'BASE_BANK_ONLINE',
    category: 'banklogs',
    bankBalance: 12450.00,
    bankAccountType: 'Savings',
    bankAccessType: 'Online Login + SMS Bypass',
    loginUsername: 'chaseuser_99',
    loginPassword: 'SecurePassword123!',
  },
  {
    id: 'bank-log-2',
    bin: 'LOGBANK',
    zip: '94105',
    bank: 'WELLS FARGO CHECKING',
    country: 'US',
    state: 'CA',
    type: 'Visa',
    creditDebit: 'Credit',
    subtype: 'Platinum',
    expDate: '07/28',
    discounted: true,
    onlyRefundable: false,
    price: 35.00,
    ssn: false,
    dob: false,
    mmn: false,
    ipAddress: '127.0.0.1',
    lastPaidAmount: false,
    driverLicense: false,
    driverLicenseScan: false,
    atmPin: false,
    attPin: false,
    fullAddress: false,
    phone: false,
    email: false,
    emailPassword: false,
    withoutCvv2: false,
    base: 'BASE_BANK_ONLINE',
    category: 'banklogs',
    bankBalance: 4850.25,
    bankAccountType: 'Checking',
    bankAccessType: 'Cookies + Login Only',
    loginUsername: 'wells_fargo_user',
    loginPassword: 'wfPassword456!',
  },
  {
    id: 'cashapp-1',
    bin: 'CASHAPP',
    zip: '30303',
    bank: 'CASHAPP VERIFIED',
    country: 'US',
    state: 'GA',
    type: 'Visa',
    creditDebit: 'Debit',
    subtype: 'Classic',
    expDate: '09/27',
    discounted: false,
    onlyRefundable: true,
    price: 20.00,
    ssn: false,
    dob: false,
    mmn: false,
    ipAddress: '127.0.0.1',
    lastPaidAmount: false,
    driverLicense: false,
    driverLicenseScan: false,
    atmPin: false,
    attPin: false,
    fullAddress: false,
    phone: false,
    email: false,
    emailPassword: false,
    withoutCvv2: false,
    base: 'BASE_CASH_MOBILE',
    category: 'cashapp',
    cashappUsername: '$cashking92',
    cashappEmail: 'cashking92@gmail.com',
    cashappPhone: '+1 404 *** ****',
    cashappPin: '4321',
    cashappHasFunds: true,
    cashappBalance: 150.00,
  },
  {
    id: 'paypal-1',
    bin: 'PAYPAL',
    zip: 'SW1A',
    bank: 'PAYPAL COOKIES + BANK',
    country: 'GB',
    state: 'LND',
    type: 'Visa',
    creditDebit: 'Credit',
    subtype: 'Platinum',
    expDate: '10/29',
    discounted: false,
    onlyRefundable: true,
    price: 25.00,
    ssn: false,
    dob: false,
    mmn: false,
    ipAddress: '127.0.0.1',
    lastPaidAmount: false,
    driverLicense: false,
    driverLicenseScan: false,
    atmPin: false,
    attPin: false,
    fullAddress: false,
    phone: false,
    email: false,
    emailPassword: false,
    withoutCvv2: false,
    base: 'BASE_PAYPAL_GLOBAL',
    category: 'paypal',
    paypalEmail: 'paypaluk_pro@domain.co.uk',
    paypalPassword: 'ppPassword789!',
    paypalCookies: 'session_cookie_token_abc123...',
    paypalHasPaymentMethod: true,
    paypalBalance: 850.00,
  },
  {
    id: 'rdp-1',
    bin: 'RDPVPS',
    zip: '60601',
    bank: 'WINDOWS SERVER CHICAGO',
    country: 'US',
    state: 'IL',
    type: 'Visa',
    creditDebit: 'Credit',
    subtype: 'Infinite',
    expDate: '12/30',
    discounted: false,
    onlyRefundable: true,
    price: 15.00,
    ssn: false,
    dob: false,
    mmn: false,
    ipAddress: '127.0.0.1',
    lastPaidAmount: false,
    driverLicense: false,
    driverLicenseScan: false,
    atmPin: false,
    attPin: false,
    fullAddress: false,
    phone: false,
    email: false,
    emailPassword: false,
    withoutCvv2: false,
    base: 'BASE_RDP_ADMIN',
    category: 'rdp',
    rdpIp: '198.51.100.42',
    rdpUsername: 'Administrator',
    rdpPassword: 'rdpSecurePassWord!',
    rdpCountry: 'US',
    rdpState: 'IL',
    rdpCity: 'Chicago',
    rdpOs: 'Windows Server 2022',
    rdpAccessType: 'Admin',
    rdpHospeed: '1 Gbps',
  }
];
